(cl:defpackage tormach_controller-msg
  (:use )
  (:export
   "<MOVEPOSEACTION>"
   "MOVEPOSEACTION"
   "<MOVEPOSEACTIONFEEDBACK>"
   "MOVEPOSEACTIONFEEDBACK"
   "<MOVEPOSEACTIONGOAL>"
   "MOVEPOSEACTIONGOAL"
   "<MOVEPOSEACTIONRESULT>"
   "MOVEPOSEACTIONRESULT"
   "<MOVEPOSEFEEDBACK>"
   "MOVEPOSEFEEDBACK"
   "<MOVEPOSEGOAL>"
   "MOVEPOSEGOAL"
   "<MOVEPOSERESULT>"
   "MOVEPOSERESULT"
   "<FORCETORQUE>"
   "FORCETORQUE"
   "<POSE>"
   "POSE"
  ))

