; Auto-generated. Do not edit!


(cl:in-package tormach_controller-msg)


;//! \htmlinclude MovePoseFeedback.msg.html

(cl:defclass <MovePoseFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass MovePoseFeedback (<MovePoseFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MovePoseFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MovePoseFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tormach_controller-msg:<MovePoseFeedback> is deprecated: use tormach_controller-msg:MovePoseFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MovePoseFeedback>) ostream)
  "Serializes a message object of type '<MovePoseFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MovePoseFeedback>) istream)
  "Deserializes a message object of type '<MovePoseFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MovePoseFeedback>)))
  "Returns string type for a message object of type '<MovePoseFeedback>"
  "tormach_controller/MovePoseFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MovePoseFeedback)))
  "Returns string type for a message object of type 'MovePoseFeedback"
  "tormach_controller/MovePoseFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MovePoseFeedback>)))
  "Returns md5sum for a message object of type '<MovePoseFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MovePoseFeedback)))
  "Returns md5sum for a message object of type 'MovePoseFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MovePoseFeedback>)))
  "Returns full string definition for message of type '<MovePoseFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MovePoseFeedback)))
  "Returns full string definition for message of type 'MovePoseFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MovePoseFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MovePoseFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MovePoseFeedback
))
