; Auto-generated. Do not edit!


(cl:in-package tormach_controller-msg)


;//! \htmlinclude MovePoseResult.msg.html

(cl:defclass <MovePoseResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:fixnum
    :initform 0))
)

(cl:defclass MovePoseResult (<MovePoseResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MovePoseResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MovePoseResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tormach_controller-msg:<MovePoseResult> is deprecated: use tormach_controller-msg:MovePoseResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <MovePoseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tormach_controller-msg:success-val is deprecated.  Use tormach_controller-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MovePoseResult>) ostream)
  "Serializes a message object of type '<MovePoseResult>"
  (cl:let* ((signed (cl:slot-value msg 'success)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MovePoseResult>) istream)
  "Deserializes a message object of type '<MovePoseResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'success) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MovePoseResult>)))
  "Returns string type for a message object of type '<MovePoseResult>"
  "tormach_controller/MovePoseResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MovePoseResult)))
  "Returns string type for a message object of type 'MovePoseResult"
  "tormach_controller/MovePoseResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MovePoseResult>)))
  "Returns md5sum for a message object of type '<MovePoseResult>"
  "0b13460cb14006d3852674b4c614f25f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MovePoseResult)))
  "Returns md5sum for a message object of type 'MovePoseResult"
  "0b13460cb14006d3852674b4c614f25f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MovePoseResult>)))
  "Returns full string definition for message of type '<MovePoseResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int8 success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MovePoseResult)))
  "Returns full string definition for message of type 'MovePoseResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int8 success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MovePoseResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MovePoseResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MovePoseResult
    (cl:cons ':success (success msg))
))
