// Generated by gencpp from file tormach_controller/MovePoseResult.msg
// DO NOT EDIT!


#ifndef TORMACH_CONTROLLER_MESSAGE_MOVEPOSERESULT_H
#define TORMACH_CONTROLLER_MESSAGE_MOVEPOSERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tormach_controller
{
template <class ContainerAllocator>
struct MovePoseResult_
{
  typedef MovePoseResult_<ContainerAllocator> Type;

  MovePoseResult_()
    : success(0)  {
    }
  MovePoseResult_(const ContainerAllocator& _alloc)
    : success(0)  {
  (void)_alloc;
    }



   typedef int8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::tormach_controller::MovePoseResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tormach_controller::MovePoseResult_<ContainerAllocator> const> ConstPtr;

}; // struct MovePoseResult_

typedef ::tormach_controller::MovePoseResult_<std::allocator<void> > MovePoseResult;

typedef boost::shared_ptr< ::tormach_controller::MovePoseResult > MovePoseResultPtr;
typedef boost::shared_ptr< ::tormach_controller::MovePoseResult const> MovePoseResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tormach_controller::MovePoseResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tormach_controller::MovePoseResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tormach_controller::MovePoseResult_<ContainerAllocator1> & lhs, const ::tormach_controller::MovePoseResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tormach_controller::MovePoseResult_<ContainerAllocator1> & lhs, const ::tormach_controller::MovePoseResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tormach_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tormach_controller::MovePoseResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tormach_controller::MovePoseResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tormach_controller::MovePoseResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tormach_controller::MovePoseResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tormach_controller::MovePoseResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tormach_controller::MovePoseResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tormach_controller::MovePoseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b13460cb14006d3852674b4c614f25f";
  }

  static const char* value(const ::tormach_controller::MovePoseResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b13460cb14006d3ULL;
  static const uint64_t static_value2 = 0x852674b4c614f25fULL;
};

template<class ContainerAllocator>
struct DataType< ::tormach_controller::MovePoseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tormach_controller/MovePoseResult";
  }

  static const char* value(const ::tormach_controller::MovePoseResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tormach_controller::MovePoseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int8 success\n"
;
  }

  static const char* value(const ::tormach_controller::MovePoseResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tormach_controller::MovePoseResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MovePoseResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tormach_controller::MovePoseResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tormach_controller::MovePoseResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<int8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TORMACH_CONTROLLER_MESSAGE_MOVEPOSERESULT_H
