// Generated by gencpp from file tormach_controller/pose.msg
// DO NOT EDIT!


#ifndef TORMACH_CONTROLLER_MESSAGE_POSE_H
#define TORMACH_CONTROLLER_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tormach_controller
{
template <class ContainerAllocator>
struct pose_
{
  typedef pose_<ContainerAllocator> Type;

  pose_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , i(0.0)
    , j(0.0)
    , k(0.0)  {
    }
  pose_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , i(0.0)
    , j(0.0)
    , k(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _i_type;
  _i_type i;

   typedef float _j_type;
  _j_type j;

   typedef float _k_type;
  _k_type k;





  typedef boost::shared_ptr< ::tormach_controller::pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tormach_controller::pose_<ContainerAllocator> const> ConstPtr;

}; // struct pose_

typedef ::tormach_controller::pose_<std::allocator<void> > pose;

typedef boost::shared_ptr< ::tormach_controller::pose > posePtr;
typedef boost::shared_ptr< ::tormach_controller::pose const> poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tormach_controller::pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tormach_controller::pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tormach_controller::pose_<ContainerAllocator1> & lhs, const ::tormach_controller::pose_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.i == rhs.i &&
    lhs.j == rhs.j &&
    lhs.k == rhs.k;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tormach_controller::pose_<ContainerAllocator1> & lhs, const ::tormach_controller::pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tormach_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tormach_controller::pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tormach_controller::pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tormach_controller::pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tormach_controller::pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tormach_controller::pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tormach_controller::pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tormach_controller::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "984c0c99d8fcaf28a3e4d0fe3ad549f2";
  }

  static const char* value(const ::tormach_controller::pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x984c0c99d8fcaf28ULL;
  static const uint64_t static_value2 = 0xa3e4d0fe3ad549f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::tormach_controller::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tormach_controller/pose";
  }

  static const char* value(const ::tormach_controller::pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tormach_controller::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 i\n"
"float32 j\n"
"float32 k\n"
;
  }

  static const char* value(const ::tormach_controller::pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tormach_controller::pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.i);
      stream.next(m.j);
      stream.next(m.k);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tormach_controller::pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tormach_controller::pose_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "i: ";
    Printer<float>::stream(s, indent + "  ", v.i);
    s << indent << "j: ";
    Printer<float>::stream(s, indent + "  ", v.j);
    s << indent << "k: ";
    Printer<float>::stream(s, indent + "  ", v.k);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TORMACH_CONTROLLER_MESSAGE_POSE_H
