# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tormach_controller/forceTorque.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class forceTorque(genpy.Message):
  _md5sum = "b67716f2ec7095782e343db5f3543a2e"
  _type = "tormach_controller/forceTorque"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 forcex
float32 forcey
float32 forcez
float32 momenti
float32 momentj
float32 momentk
"""
  __slots__ = ['forcex','forcey','forcez','momenti','momentj','momentk']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       forcex,forcey,forcez,momenti,momentj,momentk

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(forceTorque, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.forcex is None:
        self.forcex = 0.
      if self.forcey is None:
        self.forcey = 0.
      if self.forcez is None:
        self.forcez = 0.
      if self.momenti is None:
        self.momenti = 0.
      if self.momentj is None:
        self.momentj = 0.
      if self.momentk is None:
        self.momentk = 0.
    else:
      self.forcex = 0.
      self.forcey = 0.
      self.forcez = 0.
      self.momenti = 0.
      self.momentj = 0.
      self.momentk = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.forcex, _x.forcey, _x.forcez, _x.momenti, _x.momentj, _x.momentk))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.forcex, _x.forcey, _x.forcez, _x.momenti, _x.momentj, _x.momentk,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.forcex, _x.forcey, _x.forcez, _x.momenti, _x.momentj, _x.momentk))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.forcex, _x.forcey, _x.forcez, _x.momenti, _x.momentj, _x.momentk,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
