# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tormach_controller/MovePoseGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MovePoseGoal(genpy.Message):
  _md5sum = "9782a91330f66069042af5b1d4f2166d"
  _type = "tormach_controller/MovePoseGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
float32 goalx
float32 goaly
float32 goalz
float32 goali
float32 goalj
float32 goalk
float32 vel
float32 postol
float32 forcetol
"""
  __slots__ = ['goalx','goaly','goalz','goali','goalj','goalk','vel','postol','forcetol']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       goalx,goaly,goalz,goali,goalj,goalk,vel,postol,forcetol

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MovePoseGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.goalx is None:
        self.goalx = 0.
      if self.goaly is None:
        self.goaly = 0.
      if self.goalz is None:
        self.goalz = 0.
      if self.goali is None:
        self.goali = 0.
      if self.goalj is None:
        self.goalj = 0.
      if self.goalk is None:
        self.goalk = 0.
      if self.vel is None:
        self.vel = 0.
      if self.postol is None:
        self.postol = 0.
      if self.forcetol is None:
        self.forcetol = 0.
    else:
      self.goalx = 0.
      self.goaly = 0.
      self.goalz = 0.
      self.goali = 0.
      self.goalj = 0.
      self.goalk = 0.
      self.vel = 0.
      self.postol = 0.
      self.forcetol = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9f().pack(_x.goalx, _x.goaly, _x.goalz, _x.goali, _x.goalj, _x.goalk, _x.vel, _x.postol, _x.forcetol))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.goalx, _x.goaly, _x.goalz, _x.goali, _x.goalj, _x.goalk, _x.vel, _x.postol, _x.forcetol,) = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9f().pack(_x.goalx, _x.goaly, _x.goalz, _x.goali, _x.goalj, _x.goalk, _x.vel, _x.postol, _x.forcetol))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.goalx, _x.goaly, _x.goalz, _x.goali, _x.goalj, _x.goalk, _x.vel, _x.postol, _x.forcetol,) = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9f = None
def _get_struct_9f():
    global _struct_9f
    if _struct_9f is None:
        _struct_9f = struct.Struct("<9f")
    return _struct_9f
